### PR TITLE
The plugin couldn't work with some kind of secret

### PR DESCRIPTION
**Pull request by fleeto**
Here are the examples

[Empty secret](https://gist.github.com/fleeto/8fd9a0f0217070bc898d74095457a17a)

[Illegal charactor](https://gist.github.com/fleeto/2a5332e3cae0a1e582c36cdbb7530e98)

### CODE REVIEW

**Comment by elsesiy** [comment]
Thanks for this contribution. This is the first time I see an empty secret, what's the use case for that? I'll investigate the side effects of changing the encoding.

**Comment by fleeto** [comment]
> Thanks for this contribution. This is the first time I see an empty secret, what's the use case for that? I'll investigate the side effects of changing the encoding.

They come from [Banzai Logging-Operator](https://github.com/banzaicloud/logging-operator/blob/master/docs/deploy/README.md#Deploy-logging-operator-with-Helm), I think the empty one is a placeholder.

**Comment by elsesiy** [comment]
@fleeto I understand your use case but I need to properly test this. Changing the encoding and optimizing for your specific use case may not work for others. I intentionally use URLEncoding as my primary use case has always been connection strings.

**Comment by elsesiy** [comment]
I addressed these in 86dd1eb946c92e41e9e09c09a115d08ce0f78232, thanks for catching this!

**Pull request closed without merging**
